version: "3.8"

services:
  night-tasker-postgres:
    container_name: night-tasker-postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: $DB_POSTGRES_USERNAME
      POSTGRES_PASSWORD: $DB_POSTGRES_PASSWORD
    ports:
      - 5432:5432

  night-tasker-frontend-react-app:
    container_name: night-tasker-frontend-react-app
    build:
      context: ../../frontend/react-app/src
      dockerfile: ../infra/Dockerfile
      args:
        API_PATH: $API_PATH
    ports:
      - 3000:80

  night-tasker-api-gateway:
    container_name: night-tasker-api-gateway
    build:
      context: ../../backend/api-gateways/api-gateway/src
      dockerfile: ../infra/Dockerfile
    ports:
      - 5000:8080
    environment:
      RouteConfigurationSettings__Identity__Host: $IDENTITY_MICROSERVICE_PATH
      RouteConfigurationSettings__UserHub__Host: $USER_HUB_MICROSERVICE_PATH

  night-tasker-identity:
    container_name: night-tasker-identity
    build:
      context: ../../backend/identity/src
      dockerfile: ../infra/Dockerfile
    ports:
      - 5001:8080
    environment:
      ConnectionStrings__Database: $IDENTITY_DB_POSTGRES_CONNECTION_STRING
      RabbitMqSettings__Username: $RABBITMQ_USERNAME
      RabbitMqSettings__Password: $RABBITMQ_PASSWORD
      RabbitMqSettings__Host: $RABBITMQ_HOST
      RabbitMqSettings__VirtualHost: $RABBITMQ_VIRTUALHOST
      RabbitMqSettings__Port: $RABBITMQ_PORT

  night-tasker-user-hub:
    container_name: night-tasker-user-hub
    build:
      context: ../../backend/user-hub/src
      dockerfile: ../infra/Dockerfile
    ports:
      - 5002:8080
    environment:
      ConnectionStrings__Database: $USER_HUB_DB_POSTGRES_CONNECTION_STRING
      RabbitMqSettings__Username: $RABBITMQ_USERNAME
      RabbitMqSettings__Password: $RABBITMQ_PASSWORD
      RabbitMqSettings__Host: $RABBITMQ_HOST
      RabbitMqSettings__VirtualHost: $RABBITMQ_VIRTUALHOST
      RabbitMqSettings__Port: $RABBITMQ_PORT
      StorageGrpcSettings__Host: $STORAGE_GRPC_HOST
      StorageGrpcSettings__Port: $STORAGE_GRPC_PORT
      StorageGrpcSettings__BucketName: $STORAGE_GRPC_BUCKET_NAME

  night-tasker-storage:
    container_name: night-tasker-storage
    build:
      context: ../../backend/storage/src
      dockerfile: ../infra/Dockerfile
    ports:
      - 5003:5003
      - 5004:5004
    environment:
      RabbitMqSettings__Username: $RABBITMQ_USERNAME
      RabbitMqSettings__Password: $RABBITMQ_PASSWORD
      RabbitMqSettings__Host: $RABBITMQ_HOST
      RabbitMqSettings__VirtualHost: $RABBITMQ_VIRTUALHOST
      RabbitMqSettings__Port: $RABBITMQ_PORT
      MinioSettings__Endpoint: $MINIO_ENDPOINT
      MinioSettings__AccessKey: $MINIO_ACCESS_KEY
      MinioSettings__SecretKey: $MINIO_SECRET_KEY
      MinioSettings__PreSignedObjectsExpiryRange: $MINIO_PRE_SIGNED_OBJECTS_EXPIRY_RANGE

  night-tasker-rabbit-mq:
    container_name: night-tasker-rabbit-mq
    image: masstransit/rabbitmq:3.12
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USERNAME
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD

  night-tasker-minio:
    container_name: night-tasker-minio
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: $MINIO_ACCESS_KEY
      MINIO_ROOT_PASSWORD: $MINIO_SECRET_KEY
    volumes:
      - ~/data1:/data

volumes:
  data1:
