version: "3.8"

services:
  night-tasker-postgres:
    container_name: night-tasker-postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: $DB_POSTGRES_USERNAME
      POSTGRES_PASSWORD: $DB_POSTGRES_PASSWORD
    ports:
      - 5432:5432

  night-tasker-frontend-react-app:
    container_name: night-tasker-frontend-react-app
    build:
      context: ../../frontend/react-app/src
      dockerfile: ../infra/Dockerfile
      args:
        API_PATH: $API_PATH
    ports:
      - 3000:80

  night-tasker-api-gateway:
    container_name: night-tasker-api-gateway
    build:
      context: ../../backend/api-gateways/api-gateway/src
      dockerfile: ../infra/Dockerfile
    ports:
      - 5000:8080
    environment:
      RouteConfigurationSettings__Identity__Host: $IDENTITY_MICROSERVICE_PATH
      RouteConfigurationSettings__UserHub__Host: $USER_HUB_MICROSERVICE_PATH

  night-tasker-identity:
    container_name: night-tasker-identity
    build:
      context: ../../backend/identity/src
      dockerfile: ../infra/Dockerfile
    ports:
      - 5001:8080
    environment:
      ConnectionStrings__Database: $IDENTITY_DB_POSTGRES_CONNECTION_STRING
      RabbitMqSettings__Username: $RABBITMQ_USERNAME
      RabbitMqSettings__Password: $RABBITMQ_PASSWORD
      RabbitMqSettings__Host: $RABBITMQ_HOST
      RabbitMqSettings__VirtualHost: $RABBITMQ_VIRTUALHOST
      RabbitMqSettings__Port: $RABBITMQ_PORT

  night-tasker-user-hub:
    container_name: night-tasker-user-hub
    build:
      context: ../../backend/user-hub/src
      dockerfile: ../infra/Dockerfile
    ports:
      - 5002:8080
    environment:
      ConnectionStrings__Database: $USER_HUB_DB_POSTGRES_CONNECTION_STRING
      RabbitMqSettings__Username: $RABBITMQ_USERNAME
      RabbitMqSettings__Password: $RABBITMQ_PASSWORD
      RabbitMqSettings__Host: $RABBITMQ_HOST
      RabbitMqSettings__VirtualHost: $RABBITMQ_VIRTUALHOST
      RabbitMqSettings__Port: $RABBITMQ_PORT

  night-tasker-rabbit-mq:
    container_name: night-tasker-rabbit-mq
    image: masstransit/rabbitmq:3.12
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USERNAME
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
